# ===================================================
# ????????? ??????????? ? POSTGRESQL
# ===================================================
# URL ????? ???? ??????. ?????????, ??? ???? 'shop_db' ???????.
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db

# ??? ???????????? ??? ??????????? ? PostgreSQL (??????????? - postgres)
spring.datasource.username=postgres

# ??? ??????, ??????? ?? ??????? ??? ????????? PostgreSQL
spring.datasource.password=admin


# ===================================================
# ????????? JPA/HIBERNATE
# ===================================================
# 'update' - ????????????? ???????/????????? ??????? ? ???? ?????? ??? ???????
spring.jpa.hibernate.ddl-auto=update

# ?????????? SQL-??????? ? ??????? (??????? ??? ???????)
spring.jpa.show-sql=true

# ???? ????????? ??????? ??? PostgreSQL (???? Spring Boot ????? ?????????? ??? ???)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===================================================
# ????????? JWT (JSON Web Token)
# ===================================================
# ????????? ???? ??? ??????? ???????. ?????? ???? ???????.
app.jwt-secret=ThisIsMySuperLongAndSecureSecretKeyForMySpringBootProjectAndItMustBeLongerThan64Chars

# ????? ????? ?????? ? ????????????? (????? - 24 ????)
app.jwt-expiration-milliseconds=86400000


# ===================================================
# ?????????????? ?????????
# ===================================================
# ???????? ?????? ??? ???????????? ????????? ???????? ? JSON
spring.jackson.serialization.fail-on-empty-beans=false